# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
 #stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
  stripe_secret_key: sk_test_rqUbPLfiaboQE6azrBIkwGZK
  stripe_publishable_key: pk_test_nSYYmqQvftYyHbv6XfIeZ1g4
SENDGRID_USERNAME: Linda21
SENDGRID_PASSWORD: Pa$$word
